EstagioGRT/Models/Caixa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EstagioGRT.Models
{
    public class Caixa
    {
        public Caixa()
        {
            int lastId = 0;
            if (GlobalVar.FluxoCaixa.Count > 0)
                lastId = GlobalVar.FluxoCaixa.Max(t => t.Id);
            this.Id = lastId + 1;
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal Valor { get; set; }
        public char Operacao { get; set; }
    }
}

EstagioGRT/Controllers/CaixaController.cs
using EstagioGRT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstagioGRT.Controllers
{
    public class CaixaController : Controller
    {
        // GET: Caixa
        public ActionResult Index()
        {
            return View();
        }
    }
}

EstagioGRT/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstagioGRT.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EstagioGRT/Controllers/api/CaixaController.cs
using EstagioGRT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Results;
using System.Web.Mvc;

namespace EstagioGRT.Controllers.api
{
    public class CaixaController : ApiController
    {
        // GET: api/Caixa
        public IHttpActionResult Get()
        {
            return Ok(GlobalVar.FluxoCaixa);
        }

        // POST: api/Caixa/Editar
       
        // POST: api/Caixa
        public IHttpActionResult Post([FromBody]Caixa caixa)
        {
            if (caixa == null)
            {
                return BadRequest("Preencha os campos.");
            }

            if (string.IsNullOrEmpty(caixa.Nome))
            {
                return BadRequest("Nome é obrigatório.");
            }

            if (caixa.Valor == 0)
            {
                return BadRequest("Valor é obrigatório.");
            }

            if (!(caixa.Operacao == 'E' || caixa.Operacao == 'S'))
            {
                return BadRequest("Operação é obrigatório.");
            }

            GlobalVar.FluxoCaixa.Add(caixa);
            return Ok(caixa);
        }

        // GET: api/Caixa/5
        [System.Web.Http.HttpGet]
        [System.Web.Http.Route("api/Caixa/Delete/{id}")]
        public void Delete(int id)//id = 3
        {
            var lista = GlobalVar.FluxoCaixa;
            for (int i = 0; i < lista.Count; i++)
            {
                if (id == lista[i].Id)
                {
                    lista.Remove(lista[i]);                    
                }                
            }
        }
    }
}

EstagioGRT/Views/Caixa/Index.cshtml
@{
    ViewBag.Title = "Fluxo de Caixa";
}

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<h2>Fluxo de Caixa</h2>

<div class="alert alert-success carregando hide">Carregando</div>
<div class="alert alert-danger error hide"></div>
<div class="alert alert-success deletado hide"><a class="close" data-dismiss="alert"> × </a>Deletado</div>

<div>
    <label>*Nome:</label>
    <br />
    <input id="nome" type="text" />
    <br />
    <label>*Valor:</label>
    <br />
    <input id="valor" type="text" />
    <br />
    <label>*Operação:</label>
    <br />
    <select id="operacao">
        <option value=" "> </option>
        <option value="E">E</option>
        <option value="S">S</option>
    </select>
    <br />
    <button id="enviar">Enviar</button>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Nome
            </th>
            <th>
                Valor
            </th>
            <th>
                Operação
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<div id="container" style="min-width: 310px; height: 300px; max-width: 600px; margin: 0 auto"></div>

@section scripts{
    <script type="text/javascript">
        function carregarLista() {
            $('.carregando').removeClass("hide");
            $.ajax({
                method: "GET",
                url: "@Html.Raw(Url.Action("","api/Caixa"))",
                data: {}
            })
            .done(function (r) {
                if (r != undefined) {
                    $('.table tbody').html("");
                    for (var i = 0; i < r.length; i++) {
                        $('.table tbody').append("<tr>");
                        $('.table tbody').append("<td>" + r[i].Id + "</td>");
                        $('.table tbody').append("<td>" + r[i].Nome + "</td>");
                        $('.table tbody').append("<td>" + r[i].Valor + "</td>");
                        $('.table tbody').append("<td>" + r[i].Operacao + "</td>");
                        $('.table tbody').append("<td>" + '<button id="deletar"data-id="' + r[i].Id + '">Deletar</button>' + "</td>");
                        $('.table tbody').append("<td>" + '<button id="editar"data-id="' + r[i].Id + '">Editar</button>' + "</td>");
                        $('.table tbody').append("</tr>");
                    }
                    $('.carregando').addClass("hide");
                }
            });
        }
        carregarLista();

        $('#enviar').on('click', function () {
            $.ajax({
                method: "POST",
                url: "@Html.Raw(Url.Action("Create","api/Caixa"))",
                data: { Nome: $('#nome').val(), Valor: $('#valor').val(), Operacao: $('#operacao').val() }
            })
            .done(function (r) {
                carregarLista();
                $('.error').addClass('hide');
                $('#nome').val(''), $('#valor').val(''), $('#operacao').val('');
            })
            .error(function (r) {
                $('.error').html(r.responseJSON.Message);
                $('.error').removeClass('hide');
            });
        });

        $('body').on('click', '#deletar', function () {
            var id = $(this).attr('data-id');
            $.ajax({
                method: "GET",
                url: "@Html.Raw(Url.Action("Delete","api/Caixa"))" + "/" + id,
                data: {},
                success: function (r) {
                    carregarLista();
                    $('.deletado').removeClass('hide');
                    $('.deletado').html(r.responseJSON.Message);
                    $('#table').remove();
                },
                error: function (r) {
                    $('.deletado').addClass('hide');
                }
            });
        });

        $('body').on('click', '#editar', function() {



        });

        Highcharts.chart('container', {
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: 0,
                plotShadow: false
            },
            title: {
                text: 'Fluxo<br>caixas<br>',
                align: 'center',
                verticalAlign: 'middle',
                y: 40
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    dataLabels: {
                        enabled: true,
                        distance: -50,
                        style: {
                            fontWeight: 'bold',
                            color: 'white'
                        }
                    },
                    startAngle: -90,
                    endAngle: 90,
                    center: ['50%', '75%']
                }
            },
            series: [{
                type: 'pie',
                name: 'Fluxo do caixa',
                innerSize: '70%',
                data: [
                    ['Entradas', 1],
                    ['Saidas', 2],  
                ]
            }]
        });
    </script>
}

EstagioGRT/Views/Home/Index.cshtml
@using EstagioGRT.Models;

@{
    ViewBag.Title = "Fluxo de Caixa";
}

<div class="jumbotron">
    <h1>Estudo GRT</h1>
</div>

<div class="row">
    <div class="col-md-4">
        @if(ViewBag.FluxoCaixa != null)
        {
            foreach(Caixa caixa in ViewBag.FluxoCaixa)
            {
                @Html.Raw(caixa.Nome);
            }
        }
    </div>
</div>

EstagioGRT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Estudo GRT", "Index", "Caixa", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Caixa", "Index", "Caixa")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Estudo GRT</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>